--------------------------------------------------------------------------------
-- LIMPIEZA DE VISTAS 
--------------------------------------------------------------------------------
DROP VIEW FORMACION_TICARUM.VW_RESERVA_VUELO_VIGENTE_PASAJERO;
DROP VIEW FORMACION_TICARUM.VWEXT_RESERVA_VUELO_PASAJERO;
DROP VIEW FORMACION_TICARUM.VWEXT_RESERVA_VUELO;
DROP VIEW FORMACION_TICARUM.VWEXT_VUELO;

--------------------------------------------------------------------------------
-- LIMPIEZA DE TABLAS MUCHOVUELO 
--------------------------------------------------------------------------------
DROP TABLE FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO CASCADE CONSTRAINTS;
DROP TABLE FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO CASCADE CONSTRAINTS;
DROP TABLE FORMACION_TICARUM.MUCHOVUELO_VUELO CASCADE CONSTRAINTS;

--------------------------------------------------------------------------------
-- LIMPIEZA DE TABLAS INTERNAS API
--------------------------------------------------------------------------------
DROP TABLE FORMACION_TICARUM.RESERVA_VUELO_PASAJERO CASCADE CONSTRAINTS;
DROP TABLE FORMACION_TICARUM.RESERVA_VUELO CASCADE CONSTRAINTS;

--------------------------------------------------------------------------------
-- TABLA VUELO
--------------------------------------------------------------------------------
CREATE TABLE FORMACION_TICARUM.MUCHOVUELO_VUELO (   
    ID VARCHAR2(36 BYTE) NOT NULL,
    FECHA_SALIDA TIMESTAMP(6) NOT NULL,
    FECHA_LLEGADA TIMESTAMP(6) NOT NULL,
    TIPO_VUELO VARCHAR2(2 BYTE) NOT NULL, -- N(acional), I(nternacional)
    ORIGEN VARCHAR2(500 BYTE) NOT NULL,
    DESTINO VARCHAR2(500 BYTE) NOT NULL,
    ESTADO_VUELO VARCHAR2(2 BYTE), -- (P)endiente, (C)ompletado, (R)etrasado, (X)cancelado
    CAPACIDAD_AVION NUMBER(5, 0) NOT NULL,
    CONSTRAINT PK_MUCHOVUELO_VUELO PRIMARY KEY (ID)
        USING INDEX TABLESPACE INDFORMACION_TICARUM  ENABLE,
    CONSTRAINT CK_MUCHOVUELO_VUELO_TIPO CHECK (TIPO_VUELO IN ('N','I')),
    CONSTRAINT CK_MUCHOVUELO_VUELO_ESTADO CHECK (ESTADO_VUELO IS NULL OR ESTADO_VUELO IN ('P','C','R','X')),
    CONSTRAINT CK_MUCHOVUELO_VUELO_FECHAS CHECK (FECHA_LLEGADA > FECHA_SALIDA)
) TABLESPACE FORMACION_TICARUM ;

COMMENT ON TABLE FORMACION_TICARUM.MUCHOVUELO_VUELO IS 'Representa un vuelo disponible para reserva dentro del sistema.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_VUELO.ID IS 'Identificador único del vuelo (UUID).';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_VUELO.FECHA_SALIDA IS 'Fecha y hora de salida programada del vuelo.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_VUELO.FECHA_LLEGADA IS 'Fecha y hora de llegada estimada del vuelo.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_VUELO.TIPO_VUELO IS 'Tipo de vuelo: N = Nacional, I = Internacional.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_VUELO.ORIGEN IS 'Aeropuerto de origen del vuelo.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_VUELO.DESTINO IS 'Aeropuerto de destino del vuelo.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_VUELO.ESTADO_VUELO IS 'Estado actual del vuelo: P = Pendiente, C = Completado, R = Retrasado, X = Cancelado.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_VUELO.CAPACIDAD_AVION IS 'Capacidad total de pasajeros del avión asignado al vuelo.';


 
INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-03-11 07:15:00', TIMESTAMP '2026-03-11 08:30:00', 'N', 'ADOLFO SUAREZ MADRID-BARAJAS (MAD)', 'BARCELONA-EL PRAT JOSEP TARRADELLAS (BCN)', 'P', 200
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-03-13 16:40:00', TIMESTAMP '2026-03-13 18:20:00', 'N', 'VALENCIA (VLC)', 'BILBAO (BIO)', 'R', 150
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-03-14 06:30:00', TIMESTAMP '2026-03-14 09:10:00', 'I', 'ADOLFO SUAREZ MADRID-BARAJAS (MAD)', 'PARIS-CHARLES DE GAULLE (CDG)', 'P', 220
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-03-15 10:20:00', TIMESTAMP '2026-03-15 13:55:00', 'I', 'BARCELONA-EL PRAT JOSEP TARRADELLAS (BCN)', 'ROMA-FIUMICINO LEONARDO DA VINCI (FCO)', 'P', 210
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-03-16 21:45:00', TIMESTAMP '2026-03-17 00:25:00', 'N', 'MALAGA-COSTA DEL SOL (AGP)', 'SANTIAGO DE COMPOSTELA (SCQ)', 'R', 170
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-03-18 08:10:00', TIMESTAMP '2026-03-18 11:40:00', 'I', 'ADOLFO SUAREZ MADRID-BARAJAS (MAD)', 'LONDRES-HEATHROW (LHR)', 'P', 230
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-03-20 09:30:00', TIMESTAMP '2026-03-20 12:55:00', 'I', 'ADOLFO SUAREZ MADRID-BARAJAS (MAD)', 'BERLIN-BRANDENBURG (BER)', 'P', 215
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-01-15 09:00:00', TIMESTAMP '2026-01-15 10:50:00', 'N', 'BARCELONA-EL PRAT JOSEP TARRADELLAS (BCN)', 'SEVILLA-SAN PABLO (SVQ)', 'C', 180
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-01-22 12:00:00', TIMESTAMP '2026-01-22 13:20:00', 'N', 'GRANADA-FEDERICO GARCIA LORCA (GRX)', 'ADOLFO SUAREZ MADRID-BARAJAS (MAD)', 'C', 140
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-03-19 18:15:00', TIMESTAMP '2026-03-19 20:40:00', 'N', 'ZARAGOZA (ZAZ)', 'PALMA DE MALLORCA (PMI)', 'X', 160
);

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_VUELO ( ID, FECHA_SALIDA, FECHA_LLEGADA, TIPO_VUELO, ORIGEN, DESTINO, ESTADO_VUELO, CAPACIDAD_AVION) VALUES (
    LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')),
    TIMESTAMP '2026-01-10 17:30:00', TIMESTAMP '2026-01-10 18:45:00', 'N', 'ADOLFO SUAREZ MADRID-BARAJAS (MAD)', 'VALENCIA (VLC)', 'C', 165
);

COMMIT;

--------------------------------------------------------------------------------
-- TABLA RESERVA_VUELO
--------------------------------------------------------------------------------
CREATE TABLE FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO (   
    ID VARCHAR2(36 BYTE) NOT NULL,
    TIPO_DOCUMENTO_TITULAR VARCHAR2(2 BYTE) NOT NULL,  -- N(NIF), E(NIE), P(PASAPORTE)
    NUMERO_DOCUMENTO_TITULAR VARCHAR2(15 BYTE) NOT NULL,
    ID_VUELO VARCHAR2(36 BYTE) NOT NULL, -- FK
    CLASE_ASIENTO_RESERVA VARCHAR2(2 BYTE) NOT NULL, -- E(conómica), (B)usiness, (P)rimera
    FECHA_RESERVA TIMESTAMP(6) NOT NULL,
    ESTADO_RESERVA VARCHAR2(2 BYTE) NOT NULL, -- A(ctiva), X(Cancelada)
    CONSTRAINT PK_MUCHOVUELO_RESERVA_VUELO PRIMARY KEY (ID)
        USING INDEX TABLESPACE INDFORMACION_TICARUM  ENABLE,
    CONSTRAINT FK_MUCHOVUELO_RESERVA_VUELO_VUELO FOREIGN KEY (ID_VUELO)
        REFERENCES MUCHOVUELO_VUELO (ID) ENABLE,
    CONSTRAINT CK_MUCHOVUELO_RESERVA_VUELO_ESTADO CHECK (ESTADO_RESERVA IN ('A','X')),
    CONSTRAINT CK_MUCHOVUELO_RESERVA_VUELO_CLASE CHECK (CLASE_ASIENTO_RESERVA IN ('E','B','P')),
    CONSTRAINT CK_MUCHOVUELO_RESERVA_VUELO_TITULAR_DOC CHECK (TIPO_DOCUMENTO_TITULAR IN ('N','E','P'))
) TABLESPACE FORMACION_TICARUM ;

COMMENT ON TABLE FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO IS 'Representa una reserva realizada para un vuelo.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO.ID IS 'Identificador único de la reserva (UUID).';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO.TIPO_DOCUMENTO_TITULAR IS 'Tipo de documento del titular de la reserva: N = NIF, E = NIE, P = Pasaporte.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO.NUMERO_DOCUMENTO_TITULAR IS 'Número de documento del titular de la reserva.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO.ID_VUELO IS 'Identificador del vuelo reservado.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO.CLASE_ASIENTO_RESERVA IS 'Clase de asiento reservada: E = Económica, B = Business, P = Primera.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO.FECHA_RESERVA IS 'Fecha y hora en la que se realiza la reserva.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO.ESTADO_RESERVA IS 'Estado de la reserva: A = Activa, X = Cancelada.';

-- INDICES
CREATE INDEX FORMACION_TICARUM.IX_FK_MUCHOVUELO_RESERVA_VUELO_VUELO ON FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO (ID_VUELO)
    TABLESPACE INDFORMACION_TICARUM;
CREATE INDEX FORMACION_TICARUM.IX_MUCHOVUELO_RESERVA_VUELO_TITULAR_RESERVA ON FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO (TIPO_DOCUMENTO_TITULAR, NUMERO_DOCUMENTO_TITULAR)
    TABLESPACE INDFORMACION_TICARUM;


--------------------------------------------------------------------------------
-- TABLA MUCHOVUELO_RESERVA_VUELO_PASAJERO
--------------------------------------------------------------------------------
CREATE TABLE FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO (  
    ID VARCHAR2(36 BYTE) NOT NULL,
    ID_RESERVA_VUELO VARCHAR2(36 BYTE) NOT NULL,
    TIPO_DOCUMENTO VARCHAR2(2 BYTE) NOT NULL, -- N(NIF), E(NIE), P(PASAPORTE)
    NUMERO_DOCUMENTO VARCHAR2(15 BYTE) NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) NOT NULL,
    PRIMER_APELLIDO VARCHAR2(100 BYTE) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(100 BYTE),
    EMAIL VARCHAR2(300 BYTE) NOT NULL,
    NACIONALIDAD VARCHAR2(300 BYTE) NOT NULL,
    CONSTRAINT PK_MUCHOVUELO_RESERVA_VUELO_PASAJERO PRIMARY KEY (ID)
        USING INDEX TABLESPACE INDFORMACION_TICARUM ENABLE,
    CONSTRAINT FK_MUCHOVUELO_MUCHOVUELO_RESERVA_VUELO_PASAJERO_RESERVA FOREIGN KEY (ID_RESERVA_VUELO)
        REFERENCES FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO (ID) ENABLE,
    CONSTRAINT CK_MUCHOVUELO_MUCHOVUELO_RESERVA_VUELO_PASAJERO_TIPO_DOCUMENTO CHECK (TIPO_DOCUMENTO IN ('N','E','P')),
) TABLESPACE FORMACION_TICARUM;

COMMENT ON TABLE FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO IS 'Pasajeros asociados a una reserva de vuelo, con los datos del momento de la reserva.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO.ID IS 'Identificador único del pasajero dentro de la reserva de vuelo (UUID).';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO.ID_RESERVA_VUELO IS 'Identificador de la reserva de vuelo a la que pertenece el pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO.TIPO_DOCUMENTO IS 'Tipo de documento del pasajero: N = NIF, E = NIE, P = Pasaporte.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO.NUMERO_DOCUMENTO IS 'Número del documento de identidad del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO.NOMBRE IS 'Nombre del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO.PRIMER_APELLIDO IS 'Primer apellido del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO.SEGUNDO_APELLIDO IS 'Segundo apellido del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO.EMAIL IS 'Correo electrónico de contacto del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO.NACIONALIDAD IS 'Nacionalidad del pasajero en el momento de la reserva.';

CREATE INDEX FORMACION_TICARUM.IX_FK_MUCHOVUELO_MUCHOVUELO_RESERVA_VUELO_PASAJERO_RESERVA ON FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO (ID_RESERVA_VUELO)
    TABLESPACE INDFORMACION_TICARUM;

CREATE INDEX FORMACION_TICARUM.IX_MUCHOVUELO_MUCHOVUELO_RESERVA_VUELO_PASAJERO_DOCUMENTO ON FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO (TIPO_DOCUMENTO, NUMERO_DOCUMENTO)
    TABLESPACE INDFORMACION_TICARUM;


--------------------------------------------------------------------------------
-- VISTA EXTERNA VUELO
--------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW FORMACION_TICARUM.VWEXT_VUELO AS
SELECT * FROM FORMACION_TICARUM.MUCHOVUELO_VUELO;
--------------------------------------------------------------------------------
-- VISTA EXTERNA RESERVA_VUELO
--------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW FORMACION_TICARUM.VWEXT_RESERVA_VUELO AS
SELECT * FROM FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO;
--------------------------------------------------------------------------------
-- VISTA EXTERNA RESERVA_VUELO_PASAJERO
--------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW FORMACION_TICARUM.VWEXT_RESERVA_VUELO_PASAJERO AS
SELECT * FROM FORMACION_TICARUM.MUCHOVUELO_RESERVA_VUELO_PASAJERO;

--------------------------------------------------------------------------------
-- TABLA INTERNA RESERVA_VUELO
--------------------------------------------------------------------------------
CREATE TABLE FORMACION_TICARUM.RESERVA_VUELO (  
    ID VARCHAR2(36 BYTE) NOT NULL,
    TIPO_DOCUMENTO_TITULAR VARCHAR2(2 BYTE) NOT NULL,  -- N(NIF), E(NIE), P(PASAPORTE)
    NUMERO_DOCUMENTO_TITULAR VARCHAR2(15 BYTE) NOT NULL,
    ID_VUELO VARCHAR2(36 BYTE) NOT NULL, -- FK sin serlo
    CLASE_ASIENTO_RESERVA VARCHAR2(2 BYTE) NOT NULL, -- E(conómica), (B)usiness, (P)rimera
    FECHA_CREACION TIMESTAMP(6) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP(6) NOT NULL,
    ESTADO_RESERVA VARCHAR2(2 BYTE) NOT NULL, -- P(endiente), A(ctiva), X(Cancelada)
    FECHA_FORMALIZACION TIMESTAMP(6),
    ID_RESERVA_FORMALIZADA VARCHAR2(36 BYTE),
    CONSTRAINT PK_RESERVA_VUELO PRIMARY KEY (ID)
        USING INDEX TABLESPACE INDFORMACION_TICARUM  ENABLE,
    CONSTRAINT CK_RESERVA_VUELO_ESTADO CHECK (ESTADO_RESERVA IN ('P','A','X')),
    CONSTRAINT CK_RESERVA_VUELO_CLASE CHECK (CLASE_ASIENTO_RESERVA IN ('E','B','P')),
    CONSTRAINT CK_RESERVA_VUELO_TITULAR_DOC CHECK (TIPO_DOCUMENTO_TITULAR IN ('N','E','P'))
) TABLESPACE FORMACION_TICARUM ;

ALTER TABLE RESERVA_VUELO ADD ERRORES VARCHAR2(1000);

COMMENT ON TABLE FORMACION_TICARUM.RESERVA_VUELO IS 'Representa una reserva realizada para un vuelo.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.ID IS 'Identificador único de la reserva (UUID).';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.TIPO_DOCUMENTO_TITULAR IS 'Tipo de documento del titular de la reserva: N = NIF, E = NIE, P = Pasaporte.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.NUMERO_DOCUMENTO_TITULAR IS 'Número de documento del titular de la reserva.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.ID_VUELO IS 'Identificador del vuelo reservado.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.CLASE_ASIENTO_RESERVA IS 'Clase de asiento reservada: E = Económica, B = Business, P = Primera.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.ESTADO_RESERVA IS 'Estado de la reserva: P = Pendiente, A = Activa, X = Cancelada.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.FECHA_CREACION IS 'Fecha y hora en la que se crea la solicitud de reserva en el API.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.FECHA_MODIFICACION IS 'Fecha y hora en la que se modifica la solicitud de reserva en el API.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.ID_RESERVA_FORMALIZADA IS 'Identificador de la reserva formalizada en la aplicación backoffice.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.FECHA_FORMALIZACION IS 'Fecha y hora en la que se formaliza la reserva en la aplicación backoffice.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO.ERRORES IS 'Errores que impiden la creacion de la reserva.';

-- INDICES
CREATE INDEX FORMACION_TICARUM.IX_FK_RESERVA_VUELO_VEXT_VUELO ON FORMACION_TICARUM.RESERVA_VUELO (ID_VUELO)
    TABLESPACE INDFORMACION_TICARUM;
CREATE INDEX FORMACION_TICARUM.IX_RESERVA_VUELO_TITULAR_RESERVA ON FORMACION_TICARUM.RESERVA_VUELO (TIPO_DOCUMENTO_TITULAR, NUMERO_DOCUMENTO_TITULAR)
    TABLESPACE INDFORMACION_TICARUM;
    
--------------------------------------------------------------------------------
-- TABLA INTERNA RESERVA_VUELO_PASAJERO
--------------------------------------------------------------------------------
CREATE TABLE FORMACION_TICARUM.RESERVA_VUELO_PASAJERO (
    ID VARCHAR2(36 BYTE) NOT NULL,
    ID_RESERVA_VUELO VARCHAR2(36 BYTE) NOT NULL,
    TIPO_DOCUMENTO VARCHAR2(2 BYTE) NOT NULL, -- N(NIF), E(NIE), P(PASAPORTE)
    NUMERO_DOCUMENTO VARCHAR2(15 BYTE) NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) NOT NULL,
    PRIMER_APELLIDO VARCHAR2(100 BYTE) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(100 BYTE),
    EMAIL VARCHAR2(300 BYTE) NOT NULL,
    NACIONALIDAD VARCHAR2(300 BYTE) NOT NULL,
    CONSTRAINT PK_RESERVA_VUELO_PASAJERO PRIMARY KEY (ID)
        USING INDEX TABLESPACE INDFORMACION_TICARUM ENABLE,
    CONSTRAINT FK_RESERVA_VUELO_PASAJERO_RESERVA
        FOREIGN KEY (ID_RESERVA_VUELO)
        REFERENCES FORMACION_TICARUM.RESERVA_VUELO (ID) ENABLE,
    CONSTRAINT CK_RESERVA_VUELO_PASAJERO_TIPO_DOC CHECK (TIPO_DOCUMENTO IN ('N','E','P')),
) TABLESPACE FORMACION_TICARUM;

COMMENT ON TABLE FORMACION_TICARUM.RESERVA_VUELO_PASAJERO IS 'Pasajeros asociados a una reserva de vuelo.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO.ID IS 'Identificador único del pasajero dentro de la reserva de vuelo (UUID).';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO.ID_RESERVA_VUELO IS 'Identificador de la reserva de vuelo a la que pertenece.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO.TIPO_DOCUMENTO IS 'Tipo de documento: N = NIF, E = NIE, P = Pasaporte.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO.NUMERO_DOCUMENTO IS 'Número del documento del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO.NOMBRE IS 'Nombre del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO.PRIMER_APELLIDO IS 'Primer apellido del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO.SEGUNDO_APELLIDO IS 'Segundo apellido del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO.EMAIL IS 'Correo electrónico de contacto del pasajero.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO.NACIONALIDAD IS 'Nacionalidad del pasajero.';

-- INDICES
CREATE INDEX FORMACION_TICARUM.IX_FK_RESERVA_VUELO_PASAJERO_RESERVA ON FORMACION_TICARUM.RESERVA_VUELO_PASAJERO (ID_RESERVA_VUELO)
    TABLESPACE INDFORMACION_TICARUM;

CREATE INDEX FORMACION_TICARUM.IX_RESERVA_VUELO_PASAJERO_DOCUMENTO ON FORMACION_TICARUM.RESERVA_VUELO_PASAJERO (TIPO_DOCUMENTO, NUMERO_DOCUMENTO)
    TABLESPACE INDFORMACION_TICARUM;

--------------------------------------------------------------------------------
-- Vista para relacionar los vuelos con las reservas vigentes de un usuario
--------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW FORMACION_TICARUM.VW_RESERVA_VUELO_VIGENTE_PASAJERO (ID, ID_VUELO, TIPO_DOCUMENTO_PASAJERO, NUMERO_DOCUMENTO_PASAJERO) AS (
    SELECT RV.ID, RV.ID_VUELO, RVP.TIPO_DOCUMENTO, RVP.NUMERO_DOCUMENTO FROM FORMACION_TICARUM.RESERVA_VUELO RV
    INNER JOIN FORMACION_TICARUM.RESERVA_VUELO_PASAJERO RVP
        ON RV.ID = RVP.ID_RESERVA_VUELO
    WHERE RV.ESTADO_RESERVA = 'P' OR RV.ESTADO_RESERVA = 'A' 
);

  
CREATE OR REPLACE FORCE VIEW FORMACION_TICARUM.VW_ALL_VUELO_PASAJERO (ID_VUELO, TIPO_DOCUMENTO_PASAJERO, NUMERO_DOCUMENTO_PASAJERO, NUMERO_RESERVAS ) AS ( 
    SELECT DISTINCT
        COALESCE(MRV.ID_VUELO, RV.ID_VUELO) AS id_vuelo,
        COALESCE(MRVP.TIPO_DOCUMENTO, RVP.TIPO_DOCUMENTO) AS tipo_documento,
        COALESCE(MRVP.NUMERO_DOCUMENTO, RVP.NUMERO_DOCUMENTO) AS numero_documento,
        COUNT(*) OVER (
            PARTITION BY
                COALESCE(MRV.ID_VUELO, RV.ID_VUELO),
                COALESCE(MRVP.TIPO_DOCUMENTO, RVP.TIPO_DOCUMENTO),
                COALESCE(MRVP.NUMERO_DOCUMENTO, RVP.NUMERO_DOCUMENTO)
        ) AS NUMERO_RESERVAS
    FROM MUCHOVUELO_RESERVA_VUELO MRV
    FULL OUTER JOIN RESERVA_VUELO RV
        ON MRV.ID = RV.ID_RESERVA_FORMALIZADA
    LEFT JOIN MUCHOVUELO_RESERVA_VUELO_PASAJERO MRVP
        ON MRV.ID = MRVP.ID_RESERVA_VUELO
    LEFT JOIN RESERVA_VUELO_PASAJERO RVP
        ON RV.ID = RVP.ID_RESERVA_VUELO
    WHERE
        ( MRV.ESTADO_RESERVA = 'A' OR MRV.ID IS NULL )
        AND ( RV.ESTADO_RESERVA IN ('P','A') OR RV.ID IS NULL )
        AND COALESCE(MRVP.TIPO_DOCUMENTO, RVP.TIPO_DOCUMENTO) IS NOT NULL
        AND COALESCE(MRVP.NUMERO_DOCUMENTO, RVP.NUMERO_DOCUMENTO) IS NOT NULL
);


CREATE OR REPLACE VIEW FORMACION_TICARUM.VW_RESERVA_VUELO_PASAJERO AS    
SELECT * FROM FORMACION_TICARUM.VWEXT_RESERVA_VUELO_PASAJERO
UNION
SELECT * FROM FORMACION_TICARUM.RESERVA_VUELO_PASAJERO;

CREATE OR REPLACE VIEW FORMACION_TICARUM.VW_RESERVA_VUELO AS
SELECT 
    rv.ID,
    rv.TIPO_DOCUMENTO_TITULAR,
    rv.NUMERO_DOCUMENTO_TITULAR,
    NVL(mvrv.ID_VUELO, rv.ID_VUELO)
    NVL(mvrv.CLASE_ASIENTO_RESERVA, rv.CLASE_ASIENTO_RESERVA),
    rv.FECHA_CREACION,
    rv.FECHA_MODIFICACION,
    NVL(mvrv.ESTADO_RESERVA, rv.ESTADO_RESERVA),
    rv.FECHA_FORMALIZACION,
    rv.ERRORES
FROM FORMACION_TICARUM.RESERVA_VUELO rv, FORMACION_TICARUM.VWEXT_RESERVA_VUELO mvrv
WHERE rp.ID_RESERVA_FORMALIZADA = mvrv.ID
UNION
SELECT 
    vwrv.ID,
    vwrv.TIPO_DOCUMENTO_TITULAR,
    vwrv.NUMERO_DOCUMENTO_TITULAR,
    vwrv.ID_VUELO,
    vwrv.CLASE_ASIENTO_RESERVA,
    vwrv.FECHA_RESERVA AS FECHA_CREACION,
    NULL AS FECHA_MODIFICACION,
    vwrv.ESTADO_RESERVA,
    NULL AS FECHA_FORMALIZACION,
    NULL AS ERRORES
FROM FORMACION_TICARUM.VWEXT_RESERVA_VUELO vwrv
where vwrv.ID NOT IN (Select rv.ID_RESERVA_FORMALIZADA FROM FORMACION_TICARUM.RESERVA_VUELO rv);

