--------------------------------------------------------------------------------
-- LIMPIEZA DE VISTAS 
--------------------------------------------------------------------------------
DROP VIEW FORMACION_TICARUM.VW_RESERVA_PARKING
DROP VIEW FORMACION_TICARUM.VWEXT_RESERVA_PARKING;
DROP VIEW FORMACION_TICARUM.VWEXT_TIPO_ESTACIONAMIENTO;

--------------------------------------------------------------------------------
-- LIMPIEZA DE TABLAS MUCHOVUELO 
--------------------------------------------------------------------------------
DROP TABLE FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING CASCADE CONSTRAINTS;
DROP TABLE FORMACION_TICARUM.MUCHOVUELO_TIPO_ESTACIONAMIENTO CASCADE CONSTRAINTS;

--------------------------------------------------------------------------------
-- LIMPIEZA DE TABLAS INTERNAS API
--------------------------------------------------------------------------------
DROP TABLE FORMACION_TICARUM.RESERVA_PARKING CASCADE CONSTRAINTS;

--------------------------------------------------------------------------------
-- TABLA MUCHOVUELO_RESERVA_PARKING
--------------------------------------------------------------------------------
CREATE TABLE FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING (   
    ID VARCHAR2(36 BYTE) NOT NULL,
    TIPO_DOCUMENTO_CLIENTE VARCHAR2(2 BYTE) NOT NULL,  -- N(NIF), E(NIE), P(PASAPORTE)
    NUMERO_DOCUMENTO_CLIENTE VARCHAR2(15 BYTE) NOT NULL,
    FECHA_INICIO TIMESTAMP(6) NOT NULL,
    FECHA_FIN TIMESTAMP(6) NOT NULL,
    ESTADO_RESERVA VARCHAR2(2 BYTE) NOT NULL, -- A(ctiva), X(Cancelada)
	IMPORTE DOUBLE NOT NULL,
    CONSTRAINT PK_MUCHOVUELO_RESERVA_PARKING PRIMARY KEY (ID),
     CONSTRAINT CK_MUCHOVUELO_RESERVA_PARKING_ESTADO CHECK (ESTADO_RESERVA IN ('A','X')),
    CONSTRAINT CK_MUCHOVUELO_RESERVA_PARKING_CLIENTE_DOC CHECK (TIPO_DOCUMENTO_CLIENTE IN ('N','E','P'))
) TABLESPACE FORMACION_TICARUM ;

COMMENT ON TABLE FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING IS 'Almacena las reservas de parking solicitadas.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING.ID IS 'Identificador único de la reserva (UUID).';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING.TIPO_DOCUMENTO_CLIENTE IS 'Tipo de documento del cliente N(NIF), E(NIE), P(PASAPORTE).';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING.NUMERO_DOCUMENTO_CLIENTE IS 'Numero de documento del cliente.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING.FECHA_INICIO IS 'Fecha de inicio de la reserva';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING.FECHA_FIN IS 'Fecha fin de la reserva.';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING.ESTADO_RESERVA IS 'Estado de la reserva A(ctiva), X(Cancelada).';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING.IMPORTE IS 'Precio total del importe de la reserva.';

--------------------------------------------------------------------------------
-- TABLA MUCHOVUELO_TIPO_ESTACIONAMIENTO
--------------------------------------------------------------------------------
CREATE TABLE FORMACION_TICARUM.MUCHOVUELO_TIPO_ESTACIONAMIENTO (   
    TIPO VARCHAR2(2 BYTE) NOT NULL,
	PRECIO DOUBLE NOT NULL,
    CONSTRAINT PK_MUCHOVUELO_TIPO_ESTACIONAMIENTO PRIMARY KEY (TIPO),
     CONSTRAINT CK_MUCHOVUELO_TIPO_ESTACIONAMIENTO_TIPO CHECK (ESTADO_RESERVA IN ('L','C'))
) TABLESPACE FORMACION_TICARUM ;

COMMENT ON TABLE FORMACION_TICARUM.MUCHOVUELO_TIPO_ESTACIONAMIENTO IS 'Contiene los tipos de estacionamientos posibles del parking junto con el precio';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_TIPO_ESTACIONAMIENTO.TIPO IS 'Tipo de estacionamiento C = CORTA_DURACION, L = LARGA_DURACION';
COMMENT ON COLUMN FORMACION_TICARUM.MUCHOVUELO_TIPO_ESTACIONAMIENTO.PRECIO IS 'Precio en euros.';

INSERT INTO FORMACION_TICARUM.MUCHOVUELO_TIPO_ESTACIONAMIENTO ( TIPO, PRECIO) VALUES ('L', 7);
INSERT INTO FORMACION_TICARUM.MUCHOVUELO_TIPO_ESTACIONAMIENTO ( TIPO, PRECIO) VALUES ('C', 0.02);

COMMIT
--------------------------------------------------------------------------------
-- TABLA INTERNA RESERVA_PARKING
--------------------------------------------------------------------------------
CREATE TABLE FORMACION_TICARUM.RESERVA_PARKING (   
    ID VARCHAR2(36 BYTE) NOT NULL,
    TIPO_DOCUMENTO_CLIENTE VARCHAR2(2 BYTE) NOT NULL,  -- N(NIF), E(NIE), P(PASAPORTE)
    NUMERO_DOCUMENTO_CLIENTE VARCHAR2(15 BYTE) NOT NULL,
    FECHA_RESERVA TIMESTAMP(6) NOT NULL,
	FECHA_MODIFICACION TIMESTAMP(6) NOT NULL,
    ESTADO_RESERVA VARCHAR2(2 BYTE) NOT NULL, -- A(ctiva), X(Cancelada)
	ID_RESERVA_FORMALIZADA VARCHAR2(36 BYTE),
	ERRORES VARCHAR2(1000),
    CONSTRAINT PK_MUCHOVUELO_RESERVA_PARKING PRIMARY KEY (ID),
     CONSTRAINT CK_MUCHOVUELO_RESERVA_PARKING_ESTADO CHECK (ESTADO_RESERVA IN ('A','X')),
    CONSTRAINT CK_MUCHOVUELO_RESERVA_PARKING_CLIENTE_DOC CHECK (TIPO_DOCUMENTO_CLIENTE IN ('N','E','P'))
) TABLESPACE FORMACION_TICARUM ;

COMMENT ON TABLE FORMACION_TICARUM.RESERVA_PARKING IS 'Almacena las reservas de parking solicitadas.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_PARKING.ID IS 'Identificador único de la reserva (UUID).';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_PARKING.TIPO_DOCUMENTO_CLIENTE IS 'Tipo de documento del cliente N(NIF), E(NIE), P(PASAPORTE).';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_PARKING.NUMERO_DOCUMENTO_CLIENTE IS 'Numero de documento del cliente.';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_PARKING.FECHA_RESERVA IS 'Fecha de RESERVA DEL PARKING';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_PARKING.ESTADO_RESERVA IS 'Estado de la reserva A(ctiva), X(Cancelada).';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_PARKING.ID_RESERVA_FORMALIZADA IS 'Id de la reserva formalizada en el BO';
COMMENT ON COLUMN FORMACION_TICARUM.RESERVA_PARKING.ERRORES IS 'Errores que impiden la creacion de la reserva.';
--------------------------------------------------------------------------------
-- VISTA EXTERNA RESERVA_PARKING
--------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW FORMACION_TICARUM.VWEXT_RESERVA_PARKING AS
SELECT * FROM FORMACION_TICARUM.MUCHOVUELO_RESERVA_PARKING;
--------------------------------------------------------------------------------
-- VISTA EXTERNA TIPO_ESTACIONAMIENTO
--------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW FORMACION_TICARUM.VWEXT_TIPO_ESTACIONAMIENTO AS
SELECT * FROM FORMACION_TICARUM.MUCHOVUELO_TIPO_ESTACIONAMIENTO;
--------------------------------------------------------------------------------
-- VISTA INTERNA RESERVA_PARKING
--------------------------------------------------------------------------------
--PENDIENTE DE ELEGIR UNO U OTRO.
CREATE OR REPLACE VIEW FORMACION_TICARUM.VW_RESERVA_PARKING AS
SELECT 
    rp.ID,
    rp.TIPO_DOCUMENTO_CLIENTE,
    rp.NUMERO_DOCUMENTO_CLIENTE,
    rp.FECHA_RESERVA,
	rp.FECHA_MODIFICACION,
    mvrp.FECHA_INICIO,
    mvrp.FECHA_FIN,
    mvrp.IMPORTE,
    rp.ESTADO_RESERVA,
    rp.ERRORES
FROM FORMACION_TICARUM.RESERVA_PARKING rp, FORMACION_TICARUM.VWEXT_RESERVA_PARKING mvrp
WHERE rp.ID_RESERVA_FORMALIZADA = mvrp.ID
UNION
SELECT 
    vwrp.ID,
    vwrp.TIPO_DOCUMENTO_CLIENTE,
    vwrp.NUMERO_DOCUMENTO_CLIENTE,
    NULL AS FECHA_RESERVA,
	NULL AS FECHA_MODIFICACION,
    vwrp.FECHA_INICIO,
    vwrp.FECHA_FIN,
    vwrp.IMPORTE,
    vwrp.ESTADO_RESERVA,
    NULL AS ERRORES
FROM FORMACION_TICARUM.VWEXT_RESERVA_PARKING vwrp
where vwrp.ID NOT IN (Select r.ID_RESERVA_FORMALIZADA FROM FORMACION_TICARUM.RESERVA_PARKING r);